services:
  server:
    image: phonebook-backend-dev
    container_name: phonebook-backend-dev
    environment:
      - MONGODB_URI
    volumes:
      - ./backend/:/usr/src/app
    # no need to expose port when using NGINX as a reverse proxy
    # ports:
    #   - 3001:3001

  client:
    image: phonebook-frontend-dev
    container_name: phonebook-frontend-dev
    volumes:
      - ./frontend/:/usr/src/app
    # no need to expose port when using NGINX as a reverse proxy
    # ports:
    #   - 5173:5173

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - server
      - client
#
# run with: docker-compose -f docker-compose.dev.yml up
# shut down with: docker-compose -f docker-compose.dev.yml down
